### ISSUE TITLE
Setting the value of a ReactiveValue inside stream callback doesn't trigger update UI.

### ISSUE THREAD

**Issue by AntonEriksson978** [lukehutch/flutter_reactive_widget#4]
Was playing around with the geolocator package and as can be seen in the code below, you can listen to your current position and update values in a callback. But its beyond me why the assignment of the ReactiveValues doesn't trigger the UI to update.

```dart
ReactiveValue<double> long = ReactiveValue(0);
ReactiveValue<double> lat = ReactiveValue(0);

initGeoLocation() {
  Geolocator.getPositionStream(locationSettings: const LocationSettings()).listen((Position position) {
    long.value = position.longitude;
    lat.value = position.latitude;
  });
}

@override
Widget build(BuildContext context) {
  return ReactiveWidget(() => Text("Lang: ${long.value} Lat: ${lat.value}"));
}
```

What worked was to use one ValueListenerBuilder instead and this triggered the ReactiveWidget to rebuild.
```dart
@override
Widget build(BuildContext context) {
  return Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      ReactiveWidget(() => Text("Lang: ${long.value}"));
      ValueListenableBuilder<double>(
        valueListenable: GPSState.lat,
        builder: (context, value, child) {
          return Text('Latitude: $value');
        },
      ),
    ],
  );
}
```

**Comment by lukehutch** [comment]
This is bizarre and interesting! Maybe `ReactiveWidget` should extend `ValueListenableBuilder` instead. However, I'd like to understand why this is happening.

Can you please set some breakpoints in the library code to try to figure out where this is breaking down?

Try setting a breakpoint here, to see if the listener is being added when the `ReactiveWidget` is being built:
https://github.com/lukehutch/flutter_reactive_widget/blob/main/lib/src/reactive_widget.dart#L101

And set a breakpoint here, to see if the listener is being called on changes:
https://github.com/lukehutch/flutter_reactive_widget/blob/main/lib/src/reactive_widget.dart#L81

**Comment by lukehutch** [comment]
Also check whether the changes are not properly triggering a rebuild, potentially because `_cachedWidget` is set when it should be `null`:
https://github.com/lukehutch/flutter_reactive_widget/blob/main/lib/src/reactive_widget.dart#L34

**Comment by lukehutch** [comment]
Might be related to #5

**Comment by lukehutch** [comment]
Hi, any updates?

**Comment by AntonEriksson978** [comment]
Well, I just use the ValueListenableBuilder when the ReactiveWidget doesn't do the trick.

**Comment by lukehutch** [comment]
OK -- but I'd love to understand why this was happening. I don't see this issue in my own code. Can you please create a small repro project for this so I can debug it?

**Comment by lukehutch** [comment]
Should be fixed, it was the same problem as #5. Fixed in v1.0.5. Thanks for the bug report!

**Comment by lukehutch** [comment]
Actually please use v1.0.7, not v1.0.5. The newer version has a better fix, after consulting with a Flutter core developer.

**Comment by lukehutch** [comment]
Hey, I came up with a much better and simpler way to do reactivity in Flutter -- check it out:

https://github.com/lukehutch/flutter_reactive_value

(The `flutter_reactive_widget` library is now deprecated, since the new solution is so much better.)

**Comment by AntonEriksson978** [comment]
@lukehutch I will definitely check it out, it looks very simple and easy to use! Shall try it out as soon as I get the chance!
