### ISSUE TITLE
Not working when using Futures

### ISSUE THREAD

**Issue by KonKri** [lukehutch/flutter_reactive_widget#5]
I have the following code in my UI:
```Dart
return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Οι Σύνδεσμοί μου",
        ),
      ),
      body: ReactiveWidget(() => Text('${clicks.value}')),
      floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.add),
          onPressed: () {
            //addClicks();
            addClicks2();
          }),
    );
```

and in my view model:
```Dart
final clicks = ReactiveValue<int>(0);

void addClicks() {
  httpService.getLinks().then((list) => clicks.value = clicks.value + 2);
}

void addClicks2() {
  clicks.value = clicks.value + 2;
}

```

Using the addClicks() method that uses Futures, upon clicking on the floating action button, the first break point to be hit, is in the UI, and not in the updating of the value.

Unlikely, using the addClicks2() method, that doesn't use Futures, works like a charm.

Any ideas?
Thanks in advance!!!

**Comment by lukehutch** [comment]
This is very strange! The listener is added when `clicks.value` is read inside `body`, when the `build` method is called -- not when `clicks.value` is modified.

Are you sure that the `then` lambda is being executed? `getLinks` is not throwing an exception, or hanging forever?

Can you please step through the `${clicks.value}` code to check that the listener is being added?

**Comment by lukehutch** [comment]
Might be related to #4

**Comment by KonKri** [comment]
I can record it if you want. I might be missing something. the ```getLinks``` is not hanging forever, just 3 seconds. data is coming from a mock api.

**Comment by lukehutch** [comment]
No need to record it, I believe you :-)  However it would be great if you could please do a bit of digging to see (1) if the listener is being added when `clicks.value` is being read, and (2) if the listener is being called when your async callback is called.

**Comment by KonKri** [comment]
Thanks for the immediate response! I really like this library and I wish that this becomes the new norm in state management. I will look into it!

**Comment by lukehutch** [comment]
Oh, thanks. I couldn't handle the complexity of existing state management approaches in Flutter -- it was all so unnecessarily complicated -- so I wrote this. I want to make it completely bug-free, so thanks for reporting this.

I suggested to the Flutter core team to add this to Flutter, and one of the core devs hated my approach, so it was vetoed :-/

**Comment by lukehutch** [comment]
Hi, any updates?

**Comment by CarstenULarsen** [comment]
The bug can be replicated using Future.delay:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_reactive_widget/flutter_reactive_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Hello World',
      home: MyHomePage(title: 'Flutter Demo Home Page!'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;
  final sanityCounter = ReactiveValue(0);

  MyHomePage({super.key, required this.title}) {
    print('MyHomePage.constructor - sanityCounter: ' +
        sanityCounter.value.toString());
    Future.delayed(const Duration(seconds: 3)).then((value) {
      sanityCounter.value = 2;
      print('======= sanityCounter: ' + sanityCounter.value.toString());
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
          child: Row(
        children: [
          ReactiveWidget(
            () => Text('sanityCounter: ' + sanityCounter.value.toString()),
          ),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: FilledButton(
              onPressed: () => sanityCounter.value++,
              child: const Text('Add 1'),
            ),
          ),
        ],
      )),
    );
  }
}
``` 

See the full example here:

https://flutlab.io/editor/582246e8-3ab9-4ae9-9283-8d8c874b8867

**Comment by lukehutch** [comment]
@CarstenULarsen Thanks for providing a complete example. However, when I run your example, it works fine. After 3 seconds, the count is set to 2 in the UI, even if I don't click on the button.

**Comment by lukehutch** [comment]
@CarstenULarsen OK, I can replicate. Basically the mouse can't be over the button when the count is set to 2. Moving the mouse over the button causes the count display to update.

No idea what is causing the issue, but now I can work on debugging this. Thanks!

**Comment by lukehutch** [comment]
Should be fixed in 1.0.5. Many thanks, @KonKri  and @CarstenULarsen!

**Comment by lukehutch** [comment]
Actually please use v1.0.7, not v1.0.5. The newer version has a better fix, after consulting with a Flutter core developer.

**Comment by CarstenULarsen** [comment]
I will give it shot. Thanks a lot for the quick response 👍

**Comment by lukehutch** [comment]
Hey, I came up with a much better and simpler way to do reactivity in Flutter -- check it out:

https://github.com/lukehutch/flutter_reactive_value

(The `flutter_reactive_widget` library is now deprecated, since the new solution is so much better.)
